### PR TITLE
Huge update

### PR DESCRIPTION
**Pull request by MaximusFT**
update packages
update react
implement airbnb eslint rules
add playground server
many others minor updates

but... can't fix this error `block is not a BlockNode`
@margox  it will be great if you look at this.

### CODE REVIEW

**Comment by luckcoding** [comment]
terrible PR

**Comment by luckcoding** [comment]
这个提交我服了-。-｜｜

**Comment by MaximusFT** [comment]
I was surprised that they immediately merged it.
I was waiting for advice on how to fix the problem that I described in the Description.
I think we need to rollback it.

**Comment by fatwong** [comment]
@margox any luck looking into the commit? 
@MaximusFT already mentioned there's some errors not yet solved
If it's true, perhaps needs to revert the changes

**Comment by XHFkindergarten** [comment]
遗憾！！！

**Pull request merged**
