### PR TITLE
feat(translations): Created dutch translation file

### PR DESCRIPTION
**Pull request by bertyhell**
I love the look of the editor, keep up the good work :D

### CODE REVIEW

**Comment by YYL1999** [comment]
please add file in braft-extensions, thanks

**Comment by bertyhell** [comment]
Could you point me to the folder where you want me to add it? I don't see any translations yet in that repo.

**Comment by YYL1999** [comment]
> Could you point me to the folder where you want me to add it? I don't see any translations yet in that repo.

https://github.com/margox/braft-extensions/blob/master/src/table/languages.js

**Comment by bertyhell** [comment]
That file only contains the translations for the "Table" plugin.

My translation file translates all strings for the whole editor, not just for the Table plugin.
So i'm unsure how to proceed.

**Pull request merged**
