### PR TITLE
Better demo code

### PR DESCRIPTION
**Pull request by fameoflight**
Mostly just formatting of demo code

### CODE REVIEW

**Comment by margox** [comment]
Hi, thanks for your work, but I am preparing to develop version 2.0 of this project, and no new minor version will be released in recent weeks, so you can wait for my development and give your suggestion

**Comment by fameoflight** [comment]
@margox when you releasing the new version?

**Comment by fameoflight** [comment]
@margox any chance you can merge this in as well?

**Comment by margox** [comment]
OK, I will merge this PR, and if you have more ideas about this project,  you can publish your own npm package and name it like 'ff-editor' or something else.

**Pull request merged**
